import { UserRole, Status, RedemptionType, Project, RedemptionRequest, User } from './types';

export const USERS: { [key: string]: User } = {
  'student1': { id: 'student1', name: 'Alex Doe', role: UserRole.STUDENT, credits: 15 },
  'student2': { id: 'student2', name: 'Ben Carter', role: UserRole.STUDENT, credits: 25 },
  'student3': { id: 'student3', name: 'Chloe Davis', role: UserRole.STUDENT, credits: 8 },
  'faculty1': { id: 'faculty1', name: 'Dr. Smith', role: UserRole.FACULTY, credits: 0 },
  'faculty2': { id: 'faculty2', name: 'Dr. Evans', role: UserRole.FACULTY, credits: 0 },
};

export const PROJECTS: Project[] = [
  {
    id: 'proj1',
    studentId: 'student1',
    title: 'AI Chatbot for Campus Info',
    description: 'A simple chatbot using React and Dialogflow to answer common questions about campus facilities.',
    githubLink: 'https://github.com/alex-doe/campus-chatbot',
    screenshotUrl: 'https://picsum.photos/400/250',
    status: Status.APPROVED,
    creditsAwarded: 10,
    submittedAt: new Date('2025-10-15T10:00:00Z'),
    facultyComments: 'Great use of Dialogflow for a practical campus tool. Well documented and cleanly implemented. Well done.',
  },
  {
    id: 'proj2',
    studentId: 'student1',
    title: 'Personal Portfolio Website',
    description: 'A responsive portfolio website built with Next.js and Tailwind CSS.',
    githubLink: 'https://github.com/alex-doe/portfolio',
    screenshotUrl: 'https://picsum.photos/400/251',
    status: Status.DENIED,
    creditsAwarded: 0,
    submittedAt: new Date('2025-11-01T14:30:00Z'),
    facultyComments: 'The project scope is too simple for credit. Consider adding more complex features like a blog with a CMS or more interactive elements.',
  },
  {
    id: 'proj3',
    studentId: 'student1',
    title: 'E-commerce Store API',
    description: 'Backend API for an e-commerce platform using Node.js, Express, and MongoDB.',
    githubLink: 'https://github.com/alex-doe/ecommerce-api',
    status: Status.PENDING,
    creditsAwarded: 0,
    submittedAt: new Date('2025-12-01T12:00:00Z'),
  },
  {
    id: 'proj4',
    studentId: 'student2',
    title: 'Mobile App for Event Management',
    description: 'A cross-platform app built with React Native and Firebase for creating and managing university events.',
    githubLink: 'https://github.com/ben-carter/event-app',
    screenshotUrl: 'https://picsum.photos/400/252',
    status: Status.APPROVED,
    creditsAwarded: 15,
    submittedAt: new Date('2025-11-20T11:00:00Z'),
    facultyComments: 'Excellent work. The app is functional, well-designed, and addresses a real need on campus. The use of Firebase for real-time updates is particularly impressive.',
  },
  {
    id: 'proj5',
    studentId: 'student2',
    title: 'Data Visualization Dashboard',
    description: 'A web-based dashboard using D3.js to visualize campus energy consumption data.',
    githubLink: 'https://github.com/ben-carter/data-viz',
    screenshotUrl: 'https://picsum.photos/400/253',
    status: Status.PENDING,
    creditsAwarded: 0,
    submittedAt: new Date('2025-11-28T09:15:00Z'),
  },
  {
    id: 'proj6',
    studentId: 'student3',
    title: 'Peer-to-Peer Tutoring Platform',
    description: 'A platform connecting students for academic help, featuring user authentication and scheduling.',
    githubLink: 'https://github.com/chloe-davis/tutor-platform',
    status: Status.PENDING,
    creditsAwarded: 0,
    submittedAt: new Date('2025-11-29T18:00:00Z'),
  },
  {
    id: 'proj7',
    studentId: 'student3',
    title: 'Campus Navigation AR App',
    description: 'An augmented reality application to help new students navigate the campus using their phone camera.',
    githubLink: 'https://github.com/chloe-davis/ar-nav',
    screenshotUrl: 'https://picsum.photos/400/254',
    status: Status.APPROVED,
    creditsAwarded: 20,
    submittedAt: new Date('2025-10-25T16:45:00Z'),
  },
  {
    id: 'proj8',
    studentId: 'student3',
    title: 'Simple Blog Engine',
    description: 'A basic blog engine with Markdown support, built with Python and Flask.',
    githubLink: 'https://github.com/chloe-davis/flask-blog',
    status: Status.DENIED,
    creditsAwarded: 0,
    submittedAt: new Date('2025-09-30T12:00:00Z'),
    facultyComments: 'While the project is functional, it doesn\'t meet the complexity requirements. The implementation is too basic and similar to tutorial projects. Please try to incorporate more unique features.',
  },
];

export const REDEMPTIONS: RedemptionRequest[] = [
  {
    id: 'redeem1',
    studentId: 'student1',
    type: RedemptionType.ALTERNATIVE_ASSESSMENT,
    creditsCost: 5,
    status: Status.APPROVED,
    requestedAt: new Date('2025-10-20T09:00:00Z'),
  },
  {
    id: 'redeem2',
    studentId: 'student1',
    type: RedemptionType.FLEXIBLE_TUTORIAL,
    creditsCost: 2,
    status: Status.PENDING,
    requestedAt: new Date('2025-12-02T10:00:00Z'),
  },
  {
    id: 'redeem3',
    studentId: 'student2',
    type: RedemptionType.ALTERNATIVE_ASSESSMENT,
    creditsCost: 5,
    status: Status.APPROVED,
    requestedAt: new Date('2025-11-22T10:00:00Z'),
  },
  {
    id: 'redeem4',
    studentId: 'student3',
    type: RedemptionType.FLEXIBLE_TUTORIAL,
    creditsCost: 2,
    status: Status.DENIED,
    requestedAt: new Date('2025-11-05T13:20:00Z'),
  },
  {
    id: 'redeem5',
    studentId: 'student3',
    type: RedemptionType.ALTERNATIVE_ASSESSMENT,
    creditsCost: 5,
    status: Status.PENDING,
    requestedAt: new Date('2025-11-30T11:00:00Z'),
  },
];

export const CREDIT_COSTS = {
    [RedemptionType.ALTERNATIVE_ASSESSMENT]: 5,
    [RedemptionType.FLEXIBLE_TUTORIAL]: 2,
};